# Generated by Django 3.0.6 on 2020-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
