# Generated by Django 3.0.6 on 2020-06-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200616_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, help_text='BYN', null=True, verbose_name='Цена'),
        ),
    ]
