# Generated by Django 3.0.6 on 2020-06-16 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200616_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 16, 18, 41, 57, 41155, tzinfo=utc), verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
