# Generated by Django 3.0.6 on 2020-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
