# Generated by Django 3.0.6 on 2020-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_books_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен к заказу (да/нет)'),
        ),
    ]
