# Generated by Django 3.0.6 on 2020-06-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200621_2148'),
        ('books', '0008_books_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authors.Authors', verbose_name='Автор'),
        ),
    ]
