# Generated by Django 3.0.6 on 2020-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200621_2148'),
        ('books', '0009_auto_20200621_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='authors.Authors', verbose_name='Автор'),
        ),
    ]
