# Generated by Django 3.0.6 on 2020-06-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200621_2148'),
        ('books', '0010_auto_20200622_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(blank=True, max_length=100, to='authors.Authors', verbose_name='Автор'),
        ),
    ]
