# Generated by Django 3.0.6 on 2020-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200621_2148'),
        ('books', '0011_auto_20200622_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='authors.Authors'),
        ),
    ]
