# Generated by Django 3.0.6 on 2020-06-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20200626_1647'),
        ('series', '0002_auto_20200626_1647'),
        ('authors', '0003_auto_20200621_2148'),
        ('books', '0012_auto_20200622_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='authors.Authors', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='publisher.Publishers', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='books',
            name='series',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='series.Series', verbose_name='Серия книги'),
        ),
    ]
