# Generated by Django 3.0.6 on 2020-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(blank=True, null=True, verbose_name='ip')),
                ('date', models.TextField(blank=True, null=True, verbose_name='time')),
                ('browser', models.TextField(blank=True, null=True, verbose_name='browser')),
            ],
        ),
    ]
