# Generated by Django 3.0.6 on 2020-06-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
