# Generated by Django 3.0.6 on 2020-06-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('genre', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='genre.Genre', verbose_name='Жанр книги')),
            ],
        ),
    ]
