# Generated by Django 3.0.6 on 2020-06-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_books_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
