# Generated by Django 3.0.6 on 2020-07-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_auto_20200710_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Отменен'), ('1', 'Новый'), ('2', 'Подтвержден'), ('3', 'В обработке'), ('4', 'Доставляется'), ('5', 'Доставлен')], default='Новый', max_length=1)),
                ('delivery_adress', models.TextField(verbose_name='Адрес доставки')),
                ('contact_phone', models.TextField(verbose_name='Номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart')),
            ],
        ),
    ]
