# Generated by Django 3.0.6 on 2020-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.TextField(max_length=40, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.TextField(max_length=120, verbose_name='Адрес доставки'),
        ),
    ]
