# Generated by Django 3.0.6 on 2020-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200716_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(max_length=40, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.CharField(max_length=120, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Отменен'), ('1', 'Новый'), ('2', 'Подтвержден'), ('3', 'В обработке'), ('4', 'Доставляется'), ('5', 'Доставлен')], default=('1', 'Новый'), max_length=1),
        ),
    ]
