# Generated by Django 3.0.6 on 2020-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200716_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.CharField(default=0, max_length=120, verbose_name='Книги'),
            preserve_default=False,
        ),
    ]
