# Generated by Django 3.0.6 on 2020-07-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
    ]
