# Generated by Django 3.0.6 on 2020-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Отменен'), ('1', 'Новый'), ('2', 'Подтвержден'), ('3', 'В обработке'), ('4', 'Доставляется'), ('5', 'Доставлен')], default=('1', 'Новый'), max_length=1),
        ),
    ]
