# Generated by Django 3.0.6 on 2020-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='biography',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Краткая биография'),
        ),
    ]
