# Generated by Django 3.0.6 on 2020-06-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20200621_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
