# Generated by Django 3.0.6 on 2020-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200621_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Краткая биография'),
        ),
    ]
