# Generated by Django 3.0.6 on 2020-06-21 08:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200621_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BY'),
        ),
    ]
