# Generated by Django 3.0.6 on 2020-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200708_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
